name: plcd
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=21.2.4
  - cudatoolkit=11.3.1
  - pytorch=1.11.0
  - python=3.10.4
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - pandas=1.5.2
  - matplotlib=3.5.1
  - scipy=1.7.3
  - scikit-image=0.19.3
  - numba=0.56.4
  - astropy=5.1
  - pyyaml=6.0
  - seaborn=0.12.1
  - pip:
    - opencv-python==4.5.5.64
    - shap==0.41.0
    - einops==0.4.1

